In [5]:
#Import required packages
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [6]:
# Getting the data ready
# Generate train dummy data for 1000 Students and dummy test for 500
#Columns :Age, Hours of Study & Avg Previous test scores
np.random.seed(2018)
train_data, test_data = np.random.random((1000, 3)), np.random.random((500, 3))
#Generate dummy results for 1000 students : Whether Passed (1) or Failed (0)
labels = np.random.randint(2, size=(1000, 1))

In [7]:
train_data

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539],
       [0.8371111 , 0.69780061, 0.80280284],
       ...,
       [0.76474832, 0.12224649, 0.06019634],
       [0.21847107, 0.57064847, 0.27701246],
       [0.97785211, 0.81210972, 0.34780075]])

In [8]:
test_data

array([[0.35981783, 0.64707122, 0.16858627],
       [0.95089881, 0.24401454, 0.39478811],
       [0.99185888, 0.01995682, 0.19105642],
       ...,
       [0.03335012, 0.35559007, 0.5386409 ],
       [0.3804594 , 0.11970055, 0.08783101],
       [0.83887832, 0.26936355, 0.90847875]])

In [9]:
#Defining the model structure with the required layers, # of neurons, activation function and optimizers
model = Sequential()
model.add(Dense(5, input_dim=3, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 20        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 1)                 5         
                                                                 
Total params: 49
Trainable params: 49
Non-trainable params: 0
_________________________________________________________________


In [11]:
#Train the model and make predictions
model.fit(train_data, labels, epochs=10, batch_size=32)

Epoch 1/10
32/32 [==============================] - 1s 1ms/step - loss: 0.7693 - accuracy: 0.5090
Epoch 2/10
32/32 [==============================] - 0s 1ms/step - loss: 0.7260 - accuracy: 0.5140
Epoch 3/10
32/32 [==============================] - 0s 1ms/step - loss: 0.7083 - accuracy: 0.5000
Epoch 4/10
32/32 [==============================] - 0s 1ms/step - loss: 0.7008 - accuracy: 0.4910
Epoch 5/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6974 - accuracy: 0.4930
Epoch 6/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6961 - accuracy: 0.4900
Epoch 7/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.4850
Epoch 8/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.4830
Epoch 9/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.4900
Epoch 10/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.4860


In [12]:
#Make predictions from the trained model
predictions = model.predict(test_data)

16/16 [==============================] - 0s 2ms/step


In [13]:
predictions

array([[0.4913262 ],
       [0.51029253],
       [0.51137066],
       [0.5076523 ],
       [0.4618711 ],
       [0.50934845],
       [0.51407677],
       [0.52173245],
       [0.5000896 ],
       [0.515321  ],
       [0.47198936],
       [0.4810569 ],
       [0.46111536],
       [0.47689116],
       [0.5172146 ],
       [0.4935028 ],
       [0.49267974],
       [0.44960904],
       [0.4913547 ],
       [0.48876303],
       [0.51087844],
       [0.43223456],
       [0.5108213 ],
       [0.48795733],
       [0.52173245],
       [0.5065291 ],
       [0.4740712 ],
       [0.4815635 ],
       [0.46127743],
       [0.45294383],
       [0.49242994],
       [0.4942819 ],
       [0.47630668],
       [0.5015189 ],
       [0.48571885],
       [0.5079881 ],
       [0.4844302 ],
       [0.487563  ],
       [0.51966244],
       [0.5135642 ],
       [0.46049213],
       [0.47077867],
       [0.46173695],
       [0.49462497],
       [0.4787263 ],
       [0.5146701 ],
       [0.5148577 ],
       [0.514

In [14]:
#Import required packages
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

# Getting the data ready
# Generate train dummy data for 1000 Students and dummy test for 500
#Columns :Age, Hours of Study & Avg Previous test scores
np.random.seed(2018)
train_data, test_data = np.random.random((1000, 3)), np.random.random((500, 3))
#Generate dummy results for 1000 students : Whether Passed (1) or Failed (0)
labels = np.random.randint(2, size=(1000, 1))

#Defining the model structure with the required layers, # of neurons, activation function and optimizers
model = Sequential()
model.add(Dense(5, input_dim=3, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#Train the model and make predictions
model.fit(train_data, labels, epochs=10, batch_size=32)

#Make predictions from the trained model
predictions = model.predict(test_data)


Epoch 1/10
32/32 [==============================] - 1s 2ms/step - loss: 0.6942 - accuracy: 0.4910
Epoch 2/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6933 - accuracy: 0.4940
Epoch 3/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6929 - accuracy: 0.5050
Epoch 4/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6926 - accuracy: 0.5190
Epoch 5/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6925 - accuracy: 0.5280
Epoch 6/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6925 - accuracy: 0.5300
Epoch 7/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6924 - accuracy: 0.5380
Epoch 8/10
32/32 [==============================] - 0s 4ms/step - loss: 0.6923 - accuracy: 0.5420
Epoch 9/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6923 - accuracy: 0.5350
Epoch 10/10
16/16 [==============================] - 0s 1ms/step


In [15]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation

np.random.seed(2018)

# Generate dummy training dataset
x_train = np.random.random((6000,10))
y_train = np.random.randint(2, size=(6000, 1))

# Generate dummy validation dataset
x_val = np.random.random((2000,10))
y_val = np.random.randint(2, size=(2000, 1))

# Generate dummy test dataset
x_test = np.random.random((2000,10))
y_test = np.random.randint(2, size=(2000, 1))

#Define the model architecture
model = Sequential()
model.add(Dense(64, input_dim=10,activation = "relu")) #Layer 1
model.add(Dense(32,activation = "relu"))               #Layer 2
model.add(Dense(16,activation = "relu"))               #Layer 3
model.add(Dense(8,activation = "relu"))                #Layer 4
model.add(Dense(4,activation = "relu"))                #Layer 5
model.add(Dense(1,activation = "sigmoid"))             #Output Layer

#Configure the model
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

#Train the model
model.fit(x_train, y_train, batch_size=64, epochs=10, validation_data=(x_val,y_val))

Epoch 1/10
94/94 [==============================] - 3s 6ms/step - loss: 0.6936 - accuracy: 0.5033 - val_loss: 0.6931 - val_accuracy: 0.5130
Epoch 2/10
94/94 [==============================] - 0s 3ms/step - loss: 0.6930 - accuracy: 0.5068 - val_loss: 0.6930 - val_accuracy: 0.5070
Epoch 3/10
94/94 [==============================] - 0s 3ms/step - loss: 0.6929 - accuracy: 0.5117 - val_loss: 0.6927 - val_accuracy: 0.5170
Epoch 4/10
94/94 [==============================] - 0s 2ms/step - loss: 0.6926 - accuracy: 0.5092 - val_loss: 0.6926 - val_accuracy: 0.5225
Epoch 5/10
94/94 [==============================] - 0s 3ms/step - loss: 0.6926 - accuracy: 0.5083 - val_loss: 0.6925 - val_accuracy: 0.5235
Epoch 6/10
94/94 [==============================] - 0s 3ms/step - loss: 0.6922 - accuracy: 0.5158 - val_loss: 0.6926 - val_accuracy: 0.5190
Epoch 7/10
94/94 [==============================] - 0s 3ms/step - loss: 0.6917 - accuracy: 0.5293 - val_loss: 0.6923 - val_accuracy: 0.5225
Epoch 8/10
94/94 [==

In [16]:
#Make predictions from the trained model
predictions = model.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [17]:
from sklearn.metrics import classification_report,confusion_matrix

In [27]:
#print(classification_report(y_test,predictions))
#r = confusion_matrix(y_test, predictions)

In [28]:
#import sklearn.metrics
#e=sklearn.metrics.multilabel_confusion_matrix(y_test, predictions, labels=["1", "0"])

Working with my dataset

In [29]:
import os
from pathlib import Path
import pandas as pd
#getting my datasets
ml51 = pd.read_csv("train.csv")
ml52 = pd.read_csv("test.csv")
import warnings
warnings.filterwarnings('ignore')

In [30]:
#Defining the model structure with the required layers, # of neurons, activation function and optimizers
model = Sequential()
model.add(Dense(5, input_dim=3, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [31]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 5)                 20        
                                                                 
 dense_13 (Dense)            (None, 4)                 24        
                                                                 
 dense_14 (Dense)            (None, 1)                 5         
                                                                 
Total params: 49
Trainable params: 49
Non-trainable params: 0
_________________________________________________________________


In [32]:
#Train the model and make predictions
model.fit(train_data, labels, epochs=10, batch_size=32)

Epoch 1/10
32/32 [==============================] - 1s 1ms/step - loss: 0.6972 - accuracy: 0.4920
Epoch 2/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6960 - accuracy: 0.4860
Epoch 3/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6955 - accuracy: 0.4890
Epoch 4/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6950 - accuracy: 0.4830
Epoch 5/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.4890
Epoch 6/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.4880
Epoch 7/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6945 - accuracy: 0.4930
Epoch 8/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.4840
Epoch 9/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6941 - accuracy: 0.4930
Epoch 10/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6941 - accuracy: 0.4950


In [33]:
#Make predictions from the trained model
predictions = model.predict(test_data)

16/16 [==============================] - 0s 1ms/step


In [34]:
predictions

array([[0.5002095 ],
       [0.49118486],
       [0.49547192],
       [0.4896206 ],
       [0.51817006],
       [0.505526  ],
       [0.49169418],
       [0.49258992],
       [0.49773836],
       [0.49656543],
       [0.4974722 ],
       [0.49198908],
       [0.48428857],
       [0.50149876],
       [0.4671584 ],
       [0.49445298],
       [0.4814535 ],
       [0.50213206],
       [0.47990003],
       [0.48588723],
       [0.4551114 ],
       [0.51686984],
       [0.4710755 ],
       [0.50654167],
       [0.4701889 ],
       [0.49300605],
       [0.5093954 ],
       [0.5001451 ],
       [0.4871435 ],
       [0.51485604],
       [0.49207047],
       [0.50453407],
       [0.51269984],
       [0.48589   ],
       [0.50699645],
       [0.46601215],
       [0.48848   ],
       [0.50048906],
       [0.48974586],
       [0.45306328],
       [0.49687946],
       [0.49739137],
       [0.4954341 ],
       [0.48996013],
       [0.502293  ],
       [0.47675475],
       [0.4863215 ],
       [0.472

In [47]:
target=ml51["Label"]
target1=x_train["Label"]
target2=x_val["Label"]
target3=x_test["Label"]

In [56]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation


# Generate dummy training dataset
x_train = ml51.sample(frac = 0.5)
y_train = target1

# Generate dummy validation dataset
x_val = ml51.sample(frac = 0.3)
y_val = target2

# Generate dummy test dataset
x_test = ml51.sample(frac = 0.2)
y_test = target3

#Define the model architecture
model = Sequential()
model.add(Dense(64, input_dim=80,activation = "relu")) #Layer 1
model.add(Dense(32,activation = "relu"))               #Layer 2
model.add(Dense(16,activation = "relu"))               #Layer 3
model.add(Dense(8,activation = "relu"))                #Layer 4
model.add(Dense(4,activation = "relu"))                #Layer 5
model.add(Dense(1,activation = "sigmoid"))             #Output Layer

#Configure the model
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

#Train the model
model.fit(x_train, y_train, batch_size=64, epochs=10, validation_data=(x_val,y_val))

Epoch 1/10
177/177 [==============================] - 2s 4ms/step - loss: 3411.2532 - accuracy: 0.0805 - val_loss: -7197.7651 - val_accuracy: 0.0069
Epoch 2/10
177/177 [==============================] - 1s 5ms/step - loss: -8506.3545 - accuracy: 0.0011 - val_loss: -29035.0703 - val_accuracy: 0.0015
Epoch 3/10
177/177 [==============================] - 1s 3ms/step - loss: -49570.6523 - accuracy: 0.0021 - val_loss: -138969.8750 - val_accuracy: 7.3594e-04
Epoch 4/10
177/177 [==============================] - 0s 3ms/step - loss: -383923.4062 - accuracy: 0.0045 - val_loss: -1083105.3750 - val_accuracy: 7.3594e-04
Epoch 5/10
177/177 [==============================] - 0s 3ms/step - loss: -2880647.7500 - accuracy: 4.4158e-04 - val_loss: -4808069.0000 - val_accuracy: 0.0028
Epoch 6/10
177/177 [==============================] - 0s 2ms/step - loss: -10445785.0000 - accuracy: 7.0653e-04 - val_loss: -14124551.0000 - val_accuracy: 7.3594e-04
Epoch 7/10
177/177 [==============================] - 0s 2

In [57]:
#Make predictions from the trained model
predictions = model.predict(x_test)

142/142 [==============================] - 0s 1ms/step


In [50]:
from sklearn.metrics import classification_report,confusion_matrix

In [58]:
cm = confusion_matrix(y_true=y_test, y_pred=predictions)

In [59]:
print(cm)

[[   0 3648    0    0    0    0    0    0    0    0    0]
 [   0    1    0    0    0    0    0    0    0    0    0]
 [   0  176    0    0    0    0    0    0    0    0    0]
 [   0   18    0    0    0    0    0    0    0    0    0]
 [   0  369    0    0    0    0    0    0    0    0    0]
 [   0    8    0    0    0    0    0    0    0    0    0]
 [   0    8    0    0    0    0    0    0    0    0    0]
 [   0   13    0    0    0    0    0    0    0    0    0]
 [   0  278    0    0    0    0    0    0    0    0    0]
 [   0    4    0    0    0    0    0    0    0    0    0]
 [   0    6    0    0    0    0    0    0    0    0    0]]


In [60]:
print(classification_report(y_true=y_test, y_pred=predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      3648
           1       0.00      1.00      0.00         1
           2       0.00      0.00      0.00       176
           3       0.00      0.00      0.00        18
           4       0.00      0.00      0.00       369
           5       0.00      0.00      0.00         8
           6       0.00      0.00      0.00         8
           7       0.00      0.00      0.00        13
          10       0.00      0.00      0.00       278
          11       0.00      0.00      0.00         4
          12       0.00      0.00      0.00         6

    accuracy                           0.00      4529
   macro avg       0.00      0.09      0.00      4529
weighted avg       0.00      0.00      0.00      4529

